### ISSUE TITLE
Info: How to Contribute

### ISSUE THREAD

**Issue by chris-alexander** [FreeCodeCampLondon/FCCLND#12]
Write a `contributing.md` file with instructions on how to contribute including:
- [x] how to fork the repo
- [x] how to make a local copy
- [x] how to track 'upstream' (i.e. the main repo)
- [x] how to create a branch for your contribution
- [x] how to push changes to your fork
- [x] how to submit a pull request

**Comment by chris-alexander** [comment]
GitHub has the option to have templates for Pull Requests and Issues, I'm thinking I could include this on this issue. It would help to simplify contributing. What do you think? @artitudinale1 @silverwedding

**Comment by dlewis87** [comment]
This would be really helpful!

**Comment by artitudinale1** [comment]
Can be an idea. Never try those: in one side they d be really useful in the other side they could be restrictive and not so flexible. It's depending even on how many people will contribute, their level and which tool they are used to. I'd may give it a try being aware that if this method doesn't work out for us, we can always change it.

**Comment by chris-alexander** [comment]
I think its more of a guideline: like the text will be pre-populated but it can be deleted and you can write your own content.

**Comment by artitudinale1** [comment]
you mean those https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by chris-alexander** [comment]
Exactly!

**Comment by artitudinale1** [comment]
I'm easy we can try and see if are working or not. I d keep it anyway flexible.....saying those are suggested guide line if you never done thi before....... then depends on people number and ability to keep communication clear.

**Comment by chris-alexander** [comment]
I decided to leave out the templates for now. Just hoping people read the guide first.

**Comment by artitudinale1** [comment]
Let's try like this we can add them later, in case. 
Seems really good - tomorrow I'm going to read it properly. Thanks Chris!
