### ISSUE TITLE
md file to explain how to fill json and class available to index ur level in FCC track

### ISSUE THREAD

**Issue by artitudinale1** [FreeCodeCampLondon/FCCLND#18]

**Comment by artitudinale1** [comment]
check https://github.com/artitudinale1/FCCLND/pull/20

**Comment by artitudinale1** [comment]
This is absolutely NOT clear, I have try to make it more clear .
Campers are able to insert more than one classes not only to show which level of the FCC track are working on but also to list part of the track completed.
Not all class are listed - just major session ones - do we need them all? 
Probably we should re-think even classes names ?

**Comment by chris-alexander** [comment]
Keeping this open because the file probably needs some editing, but at least for now we have a file in place.

**Comment by dlewis87** [comment]
I'm gonna work on this

**Comment by dlewis87** [comment]
Do you guys think this is visible enough? Maybe link to it from the main readme?

**Comment by artitudinale1** [comment]
Yep me and @chris-alexander thought that as well. We put link to how contribute - maybe under that ?

**Comment by dlewis87** [comment]
Shall I close this?

**Comment by artitudinale1** [comment]
yes please!
