### ISSUE TITLE
JS/Gulp : make sure all files are injected with Gulp

### ISSUE THREAD

**Issue by artitudinale1** [FreeCodeCampLondon/FCCLND#22]
In app/index.html we have

```
  <!-- I COULDN'T MANAGE TO INJECT THE FOLLOWING FILES WITH GULP DESPITE OVERWRITES -->
  <!-- THESE JS NEED TO BE CALLED IN THE HEADER FOR DOM MANIPULATION   -->
  <script src="../../bower_components/isotope/js/jquery-1.7.1.min.js"></script>
  <script src="../../bower_components/isotope/jquery.isotope.js"></script>
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.css" />
```

I have tried to inject those files even with Overwriting on their bower.json , I couldn't make those work.
It'd be nice to have all files injected dynamically.

**Comment by chris-alexander** [comment]
Not sure about `jQuery` but `font-awesome` requires more than just the CSS files: there are some font files which are included with it. Would it be easier if we use the minified CDN versions?

**Comment by artitudinale1** [comment]
We need font-awesome just for the icons in Campers so it's ok just to call the css I'm calling. We can use min files for dist...it d better call not min for dev. The point here that those (that are working ok) are not injected with Gulp, but manually.

**Comment by artitudinale1** [comment]
I have no clue why this isn't working as it should....so http://stackoverflow.com/questions/37425099/inject-isotope-and-font-awesome-as-bower-with-gulp ...just for reference :)

**Comment by chris-alexander** [comment]
I've partially fixed this - at least with font-awesome. When I tried with isotope it would inject but in the wrong order. I think we should revisit this once we have detached from jQuery. I also noticed we are using an outdated version of isotope?
