### ISSUE TITLE
Review copy in Main page to explain campers page filtering

### ISSUE THREAD

**Issue by artitudinale1** [FreeCodeCampLondon/FCCLND#26]
I think we d need some more copy in main page explaining that the campers page is filtering through FCC session track permit quickly to see who has complete which tracks but also who is willing to review track completed already.
For example: let's say I'm at the React projects and I completed the all FCC track until that , but I'm willing to help or collaborate with people at first stage of track (cos  maybe I want to review back) . So I think I should choose as my campers class all classes until react-proj. So include classes as html-css, FE-proj and so on...
I don't think it's clear purpose of filtering: find a someone to pair programming with.
What you think ? (if not clear we can discuss tomorrow)

**Comment by dlewis87** [comment]
This is done, right?

**Comment by artitudinale1** [comment]
Do we need to put some explanation in Main page (I mean on the landing page of web site so in JSON) as well? or it self it s clear enough?
