### ISSUE TITLE
Image Storage for Profile Pictures

### ISSUE THREAD

**Issue by chris-alexander** [FreeCodeCampLondon/FCCLND#27]
I noticed that we are storing camper profile pics in the repo. While the number of campers listed is small this is fine but as it grows we may start having issues with the size of the repo. I think there may be a size limit in place for GitHub repositories and even if there isn't: when we clone the repo we do not want to be downloading a huge folder full of images.

I would suggest that rather than uploading profile pics we could use the URL from a third party service which already has our profile pics: i.e. GitHub or Twitter.

What do you think?

**Comment by artitudinale1** [comment]
Yep I'm agree . We can suggest where upload the image.

The only side effect will be that we will have lots of external http request by the same page (if imgs are many) that will affect loading time....maybe we will need to add a lazy loading/infinite scroll effect or something similar?

**Comment by artitudinale1** [comment]
Now that we have images loading externally I would add an infinity scroll coming with Isotope http://isotope.metafizzy.co/v1/demos/infinite-scroll.html 
What you think ?

**Comment by chris-alexander** [comment]
@artitudinale1 sure. I think we can have that as a feature post-beta release :smile: I saw you have added a milestone!
